### ISSUE TITLE
Edycja głównej postaci i jej mechaniki 

### ISSUE THREAD

**Issue by adpawel** [AGH-Narzedzia-Informatyczne-2023-2024/kidang-tikus#5]
1. Zaimplementowanie odpowiedniego poruszania się. 
2. Edycja szaty graficznej użytej do stworzenia postaci.

**Comment by jaanonim** [comment]
Czy planujemy wspierać pady czy tylko klawiaturę?

**Comment by adpawel** [comment]
> Czy planujemy wspierać pady czy tylko klawiaturę?

Jest to kwestia do uzgodnienia z zespołem
